use_frameworks!

target 'SwiftyMavenlink_Tests' do
  pod 'SwiftyMavenlink', :path => '../'

  pod 'JSONRequest',   :git => 'git@github.com:hathway/JSONRequest.git'
  pod 'SwiftyJSON'
  pod 'ObjectMapper'

  pod 'Mockingjay'

end
